### ISSUE TITLE
[SUUGESTIONS] a lot suggestions

### ISSUE THREAD

**Issue by rodopoulos1** [imi-tat0r/CS2-DiscordChatSync#1]
- Add prefix to cs2 chat when sended messages on discord to cs2 
ex:
[From discord] aka: im here from discord

Support for colors too

- Change the lang for the System messaged sended to discord and change what messages will appear on discord

- Suggestion to add: Prefix for sended message cs2 to discord like:

PrefixDiscord "[Server] {steamid64} {time} aka: Hey"

- Suggestion to add to a admin only channel, so im admin and when i send message on a channel discord that im admin, will send a message as admin on cs2

**Comment by imi-tat0r** [comment]
closed in #11

**Comment by imi-tat0r** [comment]
closed in #11
