### ISSUE TITLE
[Suggestion] Administration via Discord

### ISSUE THREAD

**Issue by mavproductions** [imi-tat0r/CS2-DiscordChatSync#9]
Hey!

Thanks for this plugin. I am wondering if you could make it possible to run commands to the server from the discord channel. Commands like `!rcon exec blah` or !map <mapName> aren't recognized due to current limitations, and obviously could add a lot of usability to this already nice plugin.

Thoughts are appreciated!

**Comment by imi-tat0r** [comment]
Well. I could implement `!rcon {args}` as a way to run `Server.ExecuteCommand({args});` but I can't trigger actual commands from other plugins via chat message.
I don't know when I will add this but I had other admin stuff planned as well so I might work on it soon :)

**Comment by imi-tat0r** [comment]
added in #12
